### ISSUE TITLE
Cosmetic armor transfers between worlds

### ISSUE THREAD

**Issue by artubi** [zlainsama/CosmeticArmorReworked#1]
Only, between existing world to new world. I haven't been able to transfer it between two existing worlds.

Using:
CosmeticArmorReworked-1.7.10-v1
CosmeticArmorReworked-1.7.10-v3

Steps to reproduce:
1. Create new creative world
2. Add armor into cosmetic slots
3. Go to menu and create another world
4. Armor from previous world is still in cosmetic slots.

After transferring armor from existing to new world, armor does work as intended. It's not there just visually, you can grab it and use it as normal armor and it will work.

**Comment by zlainsama** [comment]
Thank you for the issue report.
