### ISSUE TITLE
Render thread/FATAL error on 1.16.5 on client side

### ISSUE THREAD

**Issue by iAskel** [zlainsama/CosmeticArmorReworked#104]
del

**Comment by zlainsama** [comment]
This only happens when a single packet got broadcasted to multiple clients in LAN server.
In a LAN environment, a network packet does not actually go through network but only passed around in memory, causing this type of error. This got fixed by a workaround introduced in a later version of CosmeticArmorReworked.
Are you required to use LAN? if not, try Dedicated server.

**Comment by iAskel** [comment]
> This only happens when a single packet got broadcasted to multiple clients in LAN server. In a LAN environment, a network packet to local machine does not actually go through network but only passed around in memory, causing this type of error. This got fixed by a workaround introduced in a later version of CosmeticArmorReworked. Are you required to use LAN? if not, try a Dedicated server.

I'm already honestly confused, started installing older versions of your mod, not the latest for 1.16.5 v5, but v4 and v3. At first I thought that all, the error disappeared, but then recreated the world in which I tested the mods and after a new installation of the same 5-th version of the mod, the error again no. Probably the problem was associated with some older mod, which left a trace in my test world, now I think to reinstall everything from scratch, if it appears, I'll write here )))

**Comment by iAskel** [comment]
Yes i think you right problem may in one PC i test again and now error back again. How i can fix it?

Change version v5, v4 and v3 doesnt help and reinstalling laucnher/mods/minecraft too.

**Comment by iAskel** [comment]
> This only happens when a single packet got broadcasted to multiple clients in LAN server. In a LAN environment, a network packet to local machine does not actually go through network but only passed around in memory, causing this type of error. This got fixed by a workaround introduced in a later version of CosmeticArmorReworked. Are you required to use LAN? if not, try a Dedicated server.

In later version? Maybe you just fix it in 1.16.5?

**Comment by zlainsama** [comment]
Released 1.16.5-v5a with changes from 1.18.1-v1a.
If it does not fix this, please reopen then.

**Comment by iAskel** [comment]
> Released 1.16.5-v5a with changes from 1.18.1-v1a. If it does not fix this, please reopen then.

As a result, the error appeared without your mod, it turned out to be not so easy to reproduce, so I closed the issue.
