### ISSUE TITLE
Armor disappearing

### ISSUE THREAD

**Issue by wilsondgonzales** [zlainsama/CosmeticArmorReworked#11]
Minecraft 1.10.2 

When you chose to hide armor, it also takes it away from the armor slot

Steps to reproduce

equip armor
hide pieces or armor
watch the armor slot armor disappear

this also causes the game to think you aren't wearing armor. Clicking the armor slot allows you to pick the armor piece again

**Comment by zlainsama** [comment]
I just tested in the latest forge version(1.10.2 - 12.18.1.2094) with only CosmeticArmorReworked installed.
It worked flawlessly.

Can you provide a mod list? include their versions.

**Comment by ruyanve** [comment]
We put this in our server modpack and are getting some weird results as well. Will test around a bit and report back.

**Comment by ruyanve** [comment]
Ok, so this took a while to reproduce...
For us it was Mo Bends: https://minecraft.curseforge.com/projects/mo-bends
Removed that and all was working fine.
Logs don't show anything.

Maybe give it a spin and see for yourself :-)

**Comment by zlainsama** [comment]
A version has been released to fix this.
