### ISSUE TITLE
Geckolib Incompatibility

### ISSUE THREAD

**Issue by B4nduty** [zlainsama/CosmeticArmorReworked#110]
When you put a Geckolib Armor in a Cosmetic Armor slot, it doesn't render.

![image](https://github.com/zlainsama/CosmeticArmorReworked/assets/153728621/6e0a2b73-716e-44d1-8ab4-9ed3608045cc)
![image](https://github.com/zlainsama/CosmeticArmorReworked/assets/153728621/f9365618-bf85-43eb-a0a3-7a3a09c8a0de)

**Comment by zlainsama** [comment]
The mod you are using is not mine. You should ask them about this.

**Comment by zlainsama** [comment]
On a second thought, I should make it clearer as it could be interpreted in other meanings...
I was saying you should ask the author of Cosmetic Armor [FABRIC] about this.
