### ISSUE TITLE
Needs a way to move armor button

### ISSUE THREAD

**Issue by DPxKnightxZero** [zlainsama/CosmeticArmorReworked#12]
I noticed some mods conflict with the placement can you please add support for changing button location?

**Comment by zlainsama** [comment]
Do you mean those bottom right corner to the character?

**Comment by DPxKnightxZero** [comment]
I mean when I enable the GUI button other mods use that position.

**Comment by zlainsama** [comment]
The one that looks like a shirt?

**Comment by DPxKnightxZero** [comment]
Yes.

**Comment by zlainsama** [comment]
I will add a configuration file to make it possible to change the position.

**Comment by DPxKnightxZero** [comment]
Thank you! If it is not much trouble can you also add a preview feature? I am not good at math and geometry.

**Comment by zlainsama** [comment]
I will try to make it possible to change in game, through forge's Mod Options, so that you can see the changes.

**Comment by DPxKnightxZero** [comment]
Thank you!

**Comment by zlainsama** [comment]
A version has been released for this.

**Comment by DPxKnightxZero** [comment]
ty
