### ISSUE TITLE
CAR breaks draconic evolution

### ISSUE THREAD

**Issue by Aphenon** [zlainsama/CosmeticArmorReworked#18]
Whenever Cosmetic Armor Reworked is installed it breaks Draconic Evolution Infusion crafting.

https://minecraft.curseforge.com/projects/draconic-evolution

**Comment by zlainsama** [comment]
Please include a detailed modlist, so i can try to reproduce the problem.
I have played Draconic Evolution with my friends on a server, there was no problem with Cosmetic Armor Reworked installed.

**Comment by Aphenon** [comment]
Here you go:


Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar"
autopackager-1.6.3.jar"
AutoRegLib-1.0-2.jar"
Bagginses-1.10.2-3.0.4g.jar"
Baubles-1.10.2-1.3.8.jar"
BBG-1.9.4-5.0.0.jar"
bdlib-1.12.2.17-mc1.10.2.jar"
BetterAchievements-1.10.2-0.3.2.39.jar"
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar"
BiblioCraft[v2.2.1][MC1.10.2].jar"
BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar"
BloodMagic-1.9.4-2.1.0-69.jar"
Bookshelf-1.10.2-1.4.3.338.jar"
Botania r1.9-340.jar"
BrandonsCore-1.10.2-2.1.3.82-universal.jar"
CCTweaks-1.10.2-1.3.0.jar"
Chameleon-1.10-2.2.2.jar"
ChanceCubes-1.10.2-2.3.4.171.jar"
ChestTransporter-1.10.2-2.5.6.jar"
Chisel-MC1.10.2-0.0.7.7.jar"
chiselsandbits-12.10.jar"
CodeChickenCore-1.10.2-2.4.0.101-universal.jar"
CodeChickenLib-1.10.2-2.5.2.198-universal.jar"
compatlayer-1.10-0.1.7.jar"
ComputerCraft1.80pr0.jar"
CookingForBlockheads_1.10.2-4.2.26.jar"
CosmeticArmorReworked-1.10.2-v2a.jar"
covers-0.4.1.13-mc1.10.2.jar"
CraftTweaker-1.10.2-3.0.20.jar"
DarkUtilities-1.10.2-1.1.6.99.jar"
deepresonance-1.10-1.3.1.jar"
DefaultOptions_1.10.2-6.1.5.jar"
Draconic-Evolution-1.10.2-2.0.7.168-universal.jar"
DynamicSurroundings-1.10.2-3.2.1.2.jar"
ElecCore-1.10.2-1.6.345.jar"
ElevatorMod[V.1.2.0][MC.1.10.2].jar"
EnderCore-1.10.2-0.4.1.60-beta.jar"
EnderIO-1.10.2-3.1.156.jar"
EnderStorage-1.10.2-2.2.0.96-universal.jar"
endertanks-1.10.0-1.4.8.jar"
extrautils2-1.10.2-1.2.0.jar"
ExtremeReactors-1.10.2-0.4.5.26.jar"
FastLeafDecay-v11.jar"
flatcoloredblocks-mc1.10-v4.4.jar"
foamfix-0.3.2a-law.jar"
forestry_1.10.2-5.2.17.360.jar"
FTBLib-1.10.2-3.2.9.jar"
FTBUtilities-1.10.2-3.2.9.jar"
funky-locomotion-1.10.2-alpha-0.0.3.jar"
gendustry-1.6.4.24-mc1.10.2.jar"
GraveStone Mod 1.5.9.jar"
Gravitation Suite-3.0.1.jar"
Guide-API-1.10.2-2.0.2-45.jar"
ImmersiveEngineering-0.10-56.jar"
industrialcraft-2-2.6.105-ex110.jar"
InfernalMobs-1.10.jar"
infinitylib-0.6.2.jar"
inventorysorter-1.10-0.10.0+42.jar"
InventoryTweaks-1.61-58.jar"
IronBackpacks-1.10.2-2.2.19.jar"
ironchest-1.10.2-7.0.11.797.jar"
itemscroller-1.10.2-0.7.1.jar"
IvToolkit-1.3.1-1.10.jar"
jei_1.10.2-3.14.2.401.jar"
jeibees-0.9.0.4-mc1.10.2.jar"
journeymap-1.10.2-5.4.3.jar"
JustEnoughResources-1.10.2-0.5.8.98.jar"
KleeSlabs_1.10.2-3.3.5.jar"
LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar"
LunatriusCore-1.10.2-1.1.2.38-universal.jar"
Mantle-1.10.2-1.1.4.jar"
mcjtylib-1.10-2.2.0.jar"
mdecore-1.10.2-1.5.1.jar"
Mekanism-1.10.2-9.2.1.298.jar"
MekanismGenerators-1.10.2-9.2.1.298.jar"
MekanismTools-1.10.2-9.2.1.298.jar"
Mercurius-1.10.2-1.0.2.jar"
MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar"
missing_pieces-1.10.2-4.1.1.jar"
MmmMmmMmmMmm-1.11.jar"
modnametooltip_1.10.2-1.6.0.jar"
ModTweaker2-2.0.9.jar"
Morpheus-1.10.2-3.1.12.jar"
Morph-o-Tool-1.0-12.jar"
MouseTweaks-2.6.4-mc1.10.2.jar"
MTLib-1.0.1.jar"
multistorage-1.10.0-1.2.13.jar"
natura-1.10.2-4.0.0.93.jar"
NBTEdit-1.10.2-2.0.0.jar"
netherportalfix-mc1.9.4-4.0.1.jar"
NotEnoughItems-1.10.2-2.1.3.199-universal.jar"
notenoughwands-1.10-1.4.0.jar"
OpenComputers-MC1.10.2-1.6.1.6.jar"
Pam's HarvestCraft 1.9.4-1.10.2h.jar"
platforms-1.10.0-1.2.6.jar"
PSIonicUpgrades-r1.15.jar"
Psi-r1.0-42.jar"
QuantumStorage-1.10.2-3.2.19.jar"
Quark-r1.1-70.jar"
Railcraft_1.10.2-10.0.1.jar"
RandomThings-MC1.10.2-3.7.7.jar"
rangedpumps-0.3.jar"
RebornCore-1.10.2-2.13.2.114-universal.jar"
RebornStorage-1.10.2-1.0.1.27.jar"
RecurrentComplex-1.2.7.1-1.10.jar"
RefinedRelocation-mc1.10.2-2.1.16.jar"
refinedstorage-1.2.21.jar"
Reliquary-1.10.2-1.3.3.620.jar"
rftools-1.10-5.62.jar"
rftoolsctrl-1.10-1.5.2.jar"
roots-0.208.jar"
Sanguimancy-1.10.2-2.0.2.jar"
Schematica-1.10.2-1.7.8.153-universal.jar"
shearmadness-1.10.2-1.4.1.jar"
shetiphiancore-1.10.0-3.3.7.jar"
Signals-1.10.2-0.5.0-universal.jar"
simplegenerators-1.10.2-0.10.5b.jar"
simplelabels-1-10.2-0.0.2.jar"
simpleretrogen-1.10-4.0.1+8.jar"
SoulShards-TOW-1.10.2-2.6.6-46.jar"
StacksOnStacks2-1.1.4.jar"
StevesFactoryManager-1.10.2-1.0.12.jar"
StorageDrawers-1.10.2-3.5.7.jar"
SuperCircuitMaker-1.0.4.jar"
supercraftingframe-1.10.2-1.2.1.88.jar"
TConstruct-1.10.2-2.6.2.jar"
Translocators-1.10.2-2.1.3.51-universal.jar"
unborked-1.10.2-1.80pr0-1.0.4.jar"
usefulnullifiers-1.2.1.jar"
valkyrielib-1.10.2-0.10.5e.jar"
VeinMiner-1.9-0.35.3.595+a46c1b0.jar"
Waila-1.7.0-B3_1.9.4.jar"
WailaHarvestability-mc1.10.2-1.1.9.jar"
WaterStrainer-1.9.4-1.3.2.jar"
Wawla-1.10.2-2.3.1.213.jar"
WorldEditCuiFe-v1.0.6-mf-1.10.2-12.18.2.2125.jar"
worldedit-forge-mc1.10.2-6.1.4-dist.jar"
zerocore-1.10.2-0.1.0.3.jar"
ActuallyAdditions-1.10.2-r98.jar"
ae2stuff-0.6.0.7-mc1.10.2.jar"
agricraft-2.0.0-0.6.0-a10.jar"
AkashicTome-1.0-5.jar"
AppleSkin-mc1.10.2-1.0.4.jar"
appliedenergistics2-rv4-alpha-8.jar"
ArchitectureCraft-1.7.1-mc1.10.2.jar"
Aroma1997Core-1.9.4-1.1.1.1.jar"

**Comment by zlainsama** [comment]
I cannot reproduce this with Cosmetic Armor Reworked and Draconic Evolution alongside with Ender IO(for a creative power source) and JEI(for showing recipes).
Are you sure my mod is causing this?

**Comment by Aphenon** [comment]
Well it works after removing it, the recipes in the infusion setup is simply missing whenever the mod is installed. I have no clue if this mod is the direct cause, it may as well be some oddball mod interaction.

**Comment by Aphenon** [comment]
You can forget this issue, I have updated some mods and everything works now. I do not know what caused it, but it works.
