### ISSUE TITLE
[1.11.2-v1a] You cannot change your cosmetic armor while on creative mode

### ISSUE THREAD

**Issue by starg09** [zlainsama/CosmeticArmorReworked#19]
Pretty minor, but thought about bringing it up :)

While on creative, there's no way for changing the decorative armor. May not make much sense for singleplayer, but some people on servers may want the feature without having to leave that mode (or because they cannot, depending on how the server is configured).

**Comment by zlainsama** [comment]
There is a key(default is c) you can use to bring up the gui.

**Comment by starg09** [comment]
Oh, ok. That's good to know!

In any case though, I'd like to insist on this more as a suggestion. While the keybind does work already, many people may prefer having it available visually, same as with the survival inventory. Also for modpack makers, which could benefit from not having to allocate a key for that (which, arguably, is not that necessary since the key only works on inventory; it'd still be, however, a nice choice to have).

**Comment by zlainsama** [comment]
closing this as it's 2019 now... might implement this in an addon mod.
