### ISSUE TITLE
Multi Player reset

### ISSUE THREAD

**Issue by Badcholo** [zlainsama/CosmeticArmorReworked#2]
On my server when i relog i lose all my settings, such as to not show my helmet on.
It seems to reset itself every time i relog. i have this mod installed on the server and client.

**Comment by Badcholo** [comment]
was still using v1, updating to v4, i'll try it out now

**Comment by zlainsama** [comment]
Yes, there's few bugs in previous versions. Including some syncing issues and save/load issues with custom servers.

**Comment by Badcholo** [comment]
Verified it's fixed. Thank you so much! It's really amazing. 
Anything you'd like to add to a mod showcase?

**Comment by zlainsama** [comment]
No, A normal showcase is welcome. If you want, I can put it in my project descriptions.

**Comment by Badcholo** [comment]
I'd like that. :-)

**Comment by zlainsama** [comment]
Okay :)
When you are ready, send me a video link, I will watch it and if nothing goes wrong I will put it in my project descriptions.

**Comment by Badcholo** [comment]
Just have little more editing to do, i'll post a link as soon as i get from work and finish. 10hrs of work, eat while edit, done. Turning out nice.

**Comment by Badcholo** [comment]
Mod Showcase.
https://www.youtube.com/watch?v=7dvnjv3wVaQ&feature=youtu.be

**Comment by zlainsama** [comment]
I have it added in the project description.

I would like to let you know that little button besides the four buttons are meant to be used to toggle the mod so that you can see what armor are yourself and others actually wearing, for PVP purpose.

**Comment by Badcholo** [comment]
Makes sense now, At one point i couldn't see Teenie switch to her cosmetic armor.

**Comment by Badcholo** [comment]
I'll fix it when i get home. I'll add a scene to the video and re-upload it.
Anything else i may have overlooked or you want added to the video?
Do you have a pic or avatar you'd like to use?
Did i get the name right? I could use criticism, i want to improve on my video making skills.

**Comment by Badcholo** [comment]
Updated the Mod Showcase
https://www.youtube.com/watch?v=7rVC3qNHwxE&feature=youtu.be

**Comment by zlainsama** [comment]
It's all right, I think. I have it updated in the project description. Thanks for the Mod Showcase. :)

**Comment by Badcholo** [comment]
It's the least i can do to thank you for allowing us to use your mod.
Thank you for your hard work.

**Comment by Badcholo** [comment]
The video here could use an update too.
http://www.curse.com/mc-mods/Minecraft/237307-cosmetic-armor-reworked
at least it's not showing for me.

**Comment by zlainsama** [comment]
It should be updated. Maybe you need to refresh the browser cache.

**Comment by Badcholo** [comment]
yeah, it works now, thanks

**Comment by zlainsama** [comment]
np :3
