### ISSUE TITLE
1.12 another mod icon overlapping your icon on player inventory

### ISSUE THREAD

**Issue by captcookie** [zlainsama/CosmeticArmorReworked#20]
https://cdn.discordapp.com/attachments/329036220422160384/330515846319439894/ScreenHunter_891_Jun._30_20.11.jpg

I've mentioned this to waystones mod in their issues perhaps they could resize it i dunno.

**Comment by zlainsama** [comment]
In the config file or the config gui, you can change the position of my buttons, this can be used to solve this kind of problem.
