### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheMprs** [zlainsama/CosmeticArmorReworked#21]
whenever you write /kill and have a piece of armor in the normal armor area it causes a time out and for the lowest piece of armor to dissapear

**Comment by zlainsama** [comment]
which version does this happen?

**Comment by TheMprs** [comment]
CosmeticArmorReworked-1.12-v1

**Comment by zlainsama** [comment]
I cannot reproduce this on my side.
Could you describe it more detailed? was it singleplayer or multiplayer? did it has other mods installed? if its multiplayer, was the server a non-standard forge server?

**Comment by zlainsama** [comment]
Also, try updating forge to latest version might help.

**Comment by TheMprs** [comment]
we had it on a normal forge version, we have yet to update forge but will do soon
we had simple harvest. ftb utils and veinminer installed

**Comment by LemADEC** [comment]
is that still reproduced?

**Comment by TheMprs** [comment]
bro, it has been a year, i dont even remember writing this

**Comment by zlainsama** [comment]
closing this as it's 2019 now...
