### ISSUE TITLE
[1.12] Crashing - When accessing Cosmetic Armor

### ISSUE THREAD

**Issue by Chaospudding** [zlainsama/CosmeticArmorReworked#22]
EDIT: Included harddrive info for both server and gaming PC as well.

Hi there, I'm interested in trying your mod on a server I started (that only myself and a friend play on). I've been installing mods one by one successfully until I came to this one. After popping it on, I went to access the CosmeticArmorReworked functionality, and my game immediately crashed. It appears to install fine on the server though. I have a few screenshots attached of what is happening, as well as my crash report. Additionally, I've listed the mods that I've installed up to the point where I put on CosmeticArmorReworked 1.12.

[crash-2017-08-07_23.00.35-client.txt](https://github.com/zlainsama/CosmeticArmorReworked/files/1206683/crash-2017-08-07_23.00.35-client.txt)

To provide some info on my PC and also the server I'm running on:

My PC --- Intel i7 4790k (4.0GHz) / GTX 970 Graphics / 16GB RAM / Windows 10 Pro x64 / 512GB SSD

My Home Server --- Intel Pentium G2020 (2.90GHz) / On-board graphics / 8GB RAM (using min-1GB/max-4GB for MineOS) / Ubuntu 16.04.3 / Running Server on forge 1.12-14.21.1.2443 / 64GB SSD

Let me know if you need any other information (my systems have been fully reformated and cleaned since a few days ago, so no bloatware/viruses/etc slowing them down).

- I manage to log on to the server just fine, so I opened my inventory and either pressed "C" or clicked the icon on the bottom right of my armor window to access this mods functionality.
![2](https://user-images.githubusercontent.com/1155767/29052927-92009a60-7bc7-11e7-8343-acdb9c897469.png)

- Almost immediately after doing so, my game crashes and shows the following screen. The logs above detail this more.
![0](https://user-images.githubusercontent.com/1155767/29052727-79e1164a-7bc6-11e7-89e2-90cc98a6ed7c.png)

![1](https://user-images.githubusercontent.com/1155767/29052728-79e61a78-7bc6-11e7-9b91-e16e7294bab7.png)

**Comment by zlainsama** [comment]
The 1.12.1-v1 is not compatible with 1.12.
I have removed the 1.12 tag in the curseforge project.
You might have got that version before my resolution.
You can use the 1.12-v1 for 1.12.

**Comment by Chaospudding** [comment]
Thanks zlainsama, that worked. I looked under "Files" for the specific version you mentioned (1.12-v1) and it doesn't crash anymore.
