### ISSUE TITLE
[MC: 1.12] LAN Multiplayer crash

### ISSUE THREAD

**Issue by Rafii2198** [zlainsama/CosmeticArmorReworked#23]
Always when I play on LAN and try to use Cosmetic Armor button game crash
Here crash report: https://pastebin.com/KHg5FADV

**Comment by zlainsama** [comment]
Please use the specific version (1.12-v1) for MC1.12 as 1.12.1-v1 is incompatible with MC1.12.

**Comment by zlainsama** [comment]
closing this as it's 2019 now...
