### ISSUE TITLE
Galacticcraft integration

### ISSUE THREAD

**Issue by Aphenon** [zlainsama/CosmeticArmorReworked#26]
Is it possible to get it to work with galacticcraft accessories? right now the thermal protection and oxygen accessories show even when the cosmetic armor is supposed to override.

**Comment by zlainsama** [comment]
Like any extended inventories, i will need to add specific code to deal with them, GalacticCraft's accessories is one of them.
I might add support for GalaticCraft in the furture just like the support i did for Baubles.
But with more and more extended inventories support i added, i will need to change things around to make it consistent.
