### ISSUE TITLE
[suggestion] Cosmetic Tools, a mod companion mod idea

### ISSUE THREAD

**Issue by Darkmega18** [zlainsama/CosmeticArmorReworked#27]
G'day. Firstly, I've used this mod a lot and it's definitely fun as I like wear some strong armor, but sometimes they're not the coolest looking or something looks cool but isn't quite as potent so this helps. But I was wondering if you'd be able to make a mod that lets you take tools or items and give them a texture override using a block or crafting item. Something similar to how lumien can make the portkeys from random things inherit the texture of other items as a trap.

So you could do stuff like, make a diamond sword, and then texture it with say a stick or something else of the sort to have it act and work like the base item, aka, the diamond sword and then just look like a stick in this case. Or perhaps if you've got something like heroic armory you could find a really strong weapon from there or say something out of spartan weaponry and then texture override it to look like one of the cooler swords from that mod.

Is this something that's possible to make?

**Comment by zlainsama** [comment]
It might be possible.
I was suggested before about this.
I think it might interfere with the combat cooldown system and other right click abilities sort of things if I implement it with the method I used in Cosmetic Armor Reworked.
Although i haven't tried it, but my opinion haven't changed. Sorry.

**Comment by Darkmega18** [comment]
I see. So no go? :<

**Comment by zlainsama** [comment]
Yes, sorry about that.
