### ISSUE TITLE
Button/Hotkey nonfunctional on multiplayer server

### ISSUE THREAD

**Issue by CheshireSwift** [zlainsama/CosmeticArmorReworked#28]
When running on a multiplayer server (mod on both clients and server), neither button nor hotkey show the cosmetic slots (clicking the button plays a click sound, but nothing happens).

Works fine in single player.

Server is Forge 1.12.2-14.23.5.2772. Mod version 1.12.2-v3.

**Comment by zlainsama** [comment]
Please ask your server admin to make sure the mod is also installed on the server side.

**Comment by CheshireSwift** [comment]
Looks like the mod was in the wrong directory (guessing you get that a lot? 😅)

Thanks, closing.
