### ISSUE TITLE
[Suggestion]Cosmetic baubles

### ISSUE THREAD

**Issue by Draconian4466** [zlainsama/CosmeticArmorReworked#30]
I dont know if this has beem suggested before but being able to wear baubles as cosmetic would be great cause for botania it has tons of cosmetic baubles but i dont want to waste a bauble space for it

**Comment by zlainsama** [comment]
This probably isn't the first time.
I don't have a plan for this though, Sorry.
And, do you know that you can combine Botania's cosmetic baubles with other baubles (at least those from Botania) to have their appearance overridden?

**Comment by Draconian4466** [comment]
I didn't know that but thanks for the great mod!
