### ISSUE TITLE
Cosmetic Toggle Not Working Correctly

### ISSUE THREAD

**Issue by Kirbyarm** [zlainsama/CosmeticArmorReworked#31]
So I'm playing on a server with my friend. If we both put cosmetic armor on... it works as it should for him but not for me. If I put say.. leather in my cosmetic slots and full diamond on normal slots, he will always see the leather regardless of what he toggles his cosmetic settings to.

However whenever I enabled my cosmetic appearance is also enables his cosmetic appearance, and when I disable, both of us appear to disable (does not affect him or what he sees, only what I see). this is annoying because I want to see the same way he is able to see me.

What could the issue be?

**Comment by zlainsama** [comment]
That toggle button was meant to be able to disable the mod on the client side temporarily for PVP, so that someone else couldn't sneak up to you with full powerful armor.
You don't need to use that button in a normal situation.
