### ISSUE TITLE
armors disappears (1.7.10)

### ISSUE THREAD

**Issue by LeKebabGeek** [zlainsama/CosmeticArmorReworked#35]
hello,
when I put an armor in the cosmetic slot, it replaces the armor that was on the normal armor slot, and when I chose to hide the armor, it totally removes my armor that was on the normal armor slot (no more protection) . Is there any solution?

**Comment by zlainsama** [comment]
I couldn't reproduce the problem on a clean environment.
You need to find out what mod is causing this issue with CosmeticArmorReworked first.

**Comment by zlainsama** [comment]
This might be a incompatibility problem with Armourer's Workshop, which I have applied a fix on 1.12.2.
Please let me know if this is related with Armourer's Workshop.
