### ISSUE TITLE
[Bug]cosmetic armor reworked breaks constructs armory,s 3D models

### ISSUE THREAD

**Issue by thecrescentkid** [zlainsama/CosmeticArmorReworked#36]
CosmeticArmorReworked-1.12.2-v4a.jar

**Comment by zlainsama** [comment]
I just tested with latest constructs armory, it seems nothing is wrong.
Can you describe your issue more in detail? some screenshots and a modlist would also be helpful.

**Comment by thecrescentkid** [comment]
I know now though testing it,s caused by VIC,s modern warfare, I think the mod do es some the to the player model to improve the reload animations, and that breaks armor mods like cosmetic armor, wearables, constructs armory, etc...

**Comment by zlainsama** [comment]
You should report this to the author of that mod then...
