### ISSUE TITLE
JEI Favorites List Overlaps Crafting Preview

### ISSUE THREAD

**Issue by WenXin20** [zlainsama/CosmeticArmorReworked#37]
Minecraft v1.14.4
Forge v28.1.90
Cosmetic Armor v1a

If I click on the Green Book for the Crafting Preview in the Cosmetic Armor inventory, the JEI Favorites List overlaps it. This doesn't happen in the normal player inventory.

![2019-11-20_10 37 45](https://user-images.githubusercontent.com/12000593/69258531-5ea8db80-0b82-11ea-8e05-459b18d672f9.png)

**Comment by zlainsama** [comment]
Thank you for your report.
Sorry, I am not going to fix this.
Even though I included the crafting grid and the guide book, I don't think a small 2x2 crafting grid will be used in a complex crafting.
They are there just for some simple on-the-go crafting you happen to remember before putting your cosmetic items in your cosmetic slots.

**Comment by WenXin20** [comment]
Fair enough.
