### ISSUE TITLE
Cosmetic Armor not staying after reconnect

### ISSUE THREAD

**Issue by xenoflot** [zlainsama/CosmeticArmorReworked#4]
Hi, we've recently added CosmeticArmorReworked-1.7.10-v5b to our server's pack. If a player disconnects then reconnects, the cosmetic armor is not automatically reapplied. We need to open the cosmetic armor gui for it to switch back on.

Full mod list: http://pastebin.com/qbATFKEc

Can probably arrange access to our server if needed.

**Comment by zlainsama** [comment]
Which version of forge your server is running? Is it modified?(Cauldron)
Which mode is your server running at? offline or online?
Does this happen to everyone on the server?
Can you check player data folder inside the world save if there are corresponding files(ended with .cosarmor) to each players.

**Comment by jrpoints** [comment]
Same thing on 1.8.9 server, relogging removes cosmetic armor until you go into the armor menu and toggle any of the armor pieces, then everything resets to what you had saved, until the next relog.

I'm on forge 1723 unmodified
server is online mode
and there is .cosarmor files for each player

I believe it is saving the armor settings for each player, its just not reapplying when a player logs in until they try and change something.

**Comment by telinit** [comment]
I think we have the same problem on our private server. The mod worked perfectly in offline mode but once we've changed it to online, this problem appeared

Server version: 1.7.10
Forge: 10.13.4.1614
Does this happen to everyone on the server? Yes
And the .cosarmor files are present for each player

**Comment by zlainsama** [comment]
Please check the newly released versions(1.7.10-v5c and 1.8.9-v1a) to see if it fixes this issue.

**Comment by awade33** [comment]
Hey, I just installed the version (5c) on my server and there were some issues. We couldn't log into SP at all, it would just go back to the main menu instead of loading the world. It worked fine on the server, it booted up and I could control it normally through the console, but clients couldn't connect to it. It would say 'Internal Server Error' or 'Java IO Exception'. There were no crash reports for either.

**Comment by zlainsama** [comment]
I just tested myself. I can log into SP world fine. MP part is as your description. I will fix that and push out another version.

**Comment by zlainsama** [comment]
Please check the newly released versions(1.7.10-v5d and 1.8.9-v1b), it should fix this issue.

**Comment by awade33** [comment]
The version worked fine and the bug seems to be fix.Thanks!

**Comment by zlainsama** [comment]
Thanks for the Report :)
