### ISSUE TITLE
Feature request/bug: CosmeticArmor menu shows (otherwise disabled) vanilla recipe book icon when open

### ISSUE THREAD

**Issue by kil0byt3** [zlainsama/CosmeticArmorReworked#42]
See screenshots below for issue. In regular inventory, that green book is hidden; with CosmeticArmor GUI open, it's back. Ideally we could have the CosmeticArmor GUI hide the Vanilla recipe book as well. It would be awesome if you could either create a config option in your .cfg to hide the recipe book, or somehow detect if another mod is hiding it and also hide it (harder).

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/256

Let me know if you need any info from me :)

**Comment by zlainsama** [comment]
What mod are you using to hide the book?
If I remembered correctly, there was mod that completely disables/hides the book even if it is in modded GUI.
It should be easy for me to add a config option to make it hidden.

**Comment by kil0byt3** [comment]
Quark. I'll look into other mods - ideally we'd like to keep down on our load order however.

**Comment by zlainsama** [comment]
Released 1.14.4-v2 and 1.15.2-v2 which added support for disabling the RecipeBook in the CosmeticArmorInventory.
The added config option is under server category, you can find the config file in "<the world's save folder>/serverconfig".
The reason why it is under server category is to avoid potential de-sync issues.
You will need another mod to achieve changing default values in server configs, I'm sorry about this inconvenience.

**Comment by kil0byt3** [comment]
Great!! Thank you for your help! Is it possible that this change is backported to the 1.12 version as well, or have you dropped new feature support for that version? No problem if so.   
  
  
  

  
  

  
  
>

**Comment by zlainsama** [comment]
Released 1.12.2-v5 with this change.
You will need to make sure this setting is same between client and server to avoid potential de-sync issues.

**Comment by kil0byt3** [comment]
Thanks a ton!
