### ISSUE TITLE
Issue with lang file in latest update? cos.gui.buttoncos

### ISSUE THREAD

**Issue by kil0byt3** [zlainsama/CosmeticArmorReworked#43]
Hello, see image below. The CosmeticArmor button to access the inventory seems to have incorrect lang/not assigned. Tested using only CosmeticArmor in a fresh instance.

![image](https://user-images.githubusercontent.com/39413400/79892896-18b5a500-83b8-11ea-9584-2f57469ec61f.png)

**Comment by zlainsama** [comment]
Which version are you using?

**Comment by kil0byt3** [comment]
CosmeticArmorReworked-1.12.2-v5

**Comment by zlainsama** [comment]
Release 1.12.2-v5a with re-built jar, it should fix this.

**Comment by kil0byt3** [comment]
Thank you! Working great!
