### ISSUE TITLE
Server Crash w/ Curios Toggle Buttons

### ISSUE THREAD

**Issue by WenXin20** [zlainsama/CosmeticArmorReworked#44]
`Minecraft v1.15.2`
`Forge v31.1.61`
`Curios v2.0.2.2`
`Cosmetic Armor v3`

After clicking on the Toggle Button in the Curios Inventory, my server immediately crashed...
[Crash Report](https://gist.github.com/WenXin20/02130836e88d0add11691ad1edbbe347)

**Comment by zlainsama** [comment]
Thank you.
