### ISSUE TITLE
Crash on server connect v1a

### ISSUE THREAD

**Issue by jrpoints** [zlainsama/CosmeticArmorReworked#5]
[ http://pastebin.com/MaK7HKPR ](url)

Crashed the server when I connected after updating, removed the mod and connected fine.

**Comment by zlainsama** [comment]
Can you provide the mod file to me? Or, can you try without other mods? The stacktrace doesn't match on the current source code.

**Comment by zlainsama** [comment]
Please check the newly released versions(1.7.10-v5d and 1.8.9-v1b), it should fix this issue.
