### ISSUE TITLE
It doesn't seem to be working on Curios items.

### ISSUE THREAD

**Issue by SheltieChan** [zlainsama/CosmeticArmorReworked#52]
I'm using the Tool Belt mod, I have it in my Curious slot, and when I click the lil button to toggle it into hidden mode, nothing happens.

I'm on 1.16.4.

**Comment by zlainsama** [comment]
In 1.16, those buttons are implemented by Curios itself.
Only in 1.15, those buttons are added by my mod.
You should report this to Curios.

**Comment by SheltieChan** [comment]
Ah!  Gotcha!

Will do!
