### ISSUE TITLE
curseforge issue

### ISSUE THREAD

**Issue by alamb91** [zlainsama/CosmeticArmorReworked#54]
try to install via curseforge and it says it doesn't exist

**Comment by zlainsama** [comment]
Which version of Minecraft are you trying to install it? is it Java Edition?
Which launcher are you using to install it? CurseForge on OverWolf? or Twitch?

If you are clicking on the "Install" button on the website and the launcher shows "Manifest file does not exist", then I think it is normal as CurseForge on Overwolf is still beta, they probably are still implementing things.
You need to click on a modpack inside the launcher and choose to install a mod from there.
