### ISSUE TITLE
Incompatibility with Data Terminal from AcademyCraft mod

### ISSUE THREAD

**Issue by Alaberti** [zlainsama/CosmeticArmorReworked#6]
Version: CosmeticArmorReworked-1.7.10-v5d

AcademyCraft Version: AcademyCraft-1.0pr3_1
- https://github.com/LambdaInnovation/AcademyCraft/issues/257
- http://minecraft.curseforge.com/projects/academycraft
 
There is an item in AcademyCraft called the Data Terminal which, when used, won't render its GUI with Cosmetic Armor Reworked also installed. It's a very central part of that mod - is it possible for you to look into this? I will also be making an issue on their page as well.

**Comment by zlainsama** [comment]
I just tested myself. It worked perfectly fine in my game.
![2016-02-05_21 32 02](https://cloud.githubusercontent.com/assets/3251859/12847732/39f719c0-cc50-11e5-808d-1213c18734bd.png)
![2016-02-05_21 32 06](https://cloud.githubusercontent.com/assets/3251859/12847735/3ddf6a38-cc50-11e5-9124-84c33207a743.png)
It might be some other mod that has incompatibility with AcademyCraft.

**Comment by Alaberti** [comment]
Went through all of my mods again, discovered one of the configs was corrupted. Thank you for testing as well, and I apologize for not testing deeper to confirm and prevent you from wasting your valuable time.
