### ISSUE TITLE
"Slight" incompatibility with EpicFight MOD

### ISSUE THREAD

**Issue by gaesyeah** [zlainsama/CosmeticArmorReworked#66]
this bug has already been discussed on the "epicfight" github and I'm aware that it probably won't be easy to fix, but I still decided to comment on it here to let you know about the problem:

https://github.com/Yesssssman/epicfightmod/issues/644

Thanks!

PS: my english isnt good, sorry.

**Comment by zlainsama** [comment]
A fix was released in 1.16.5 and 1.17.1.
