### ISSUE TITLE
1.17 Multiplayer failed-cannot join the room

### ISSUE THREAD

**Issue by LouiseWhite212109** [zlainsama/CosmeticArmorReworked#67]
With this mod other players can not join the room.

Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt:0

**Comment by lays24mc** [comment]
Hi, this issue starts with opening a map (also on a frame) or a buried treasure map in the player inventory. The server logs this issue: https://pastebin.com/sK5iNCyG

**Comment by mcmodderHD** [comment]
Still occuring in the newest version for 1.18.1
I found a fix, which is deleting the .cosarmor file of the joining player under "saves/<World Name>/playerdata"
(Did not try it but i guess it deletes the equipped armor)

**Comment by Elmfeather7** [comment]
Having the same issue on 1.18.1 as well, can confirm deleting the file mentioned above can fix the issue, but you have to do this every time you load into the world

**Comment by zlainsama** [comment]
@mcmodderHD @Elmfeather7 
Do they all show `refCnt: 0` in the log? server log or client log?
How frequently does this happen? everytime?

**Comment by Elmfeather7** [comment]
I'm not sure how to check that, but every time I want to have anyone connect to me (playing via LAN) I first have to delete their .cosarmor file or they wont connect at all, same everytime.

**Comment by zlainsama** [comment]
@Elmfeather7 
Thanks for your info, through it I found the cause with some help in the Forge discord.
A workaround has been added, I will release the fixed version in 1.18.1 and 1.17.1.

**Comment by Elmfeather7** [comment]
Awesome! Great work :D can't wait to download it. (of course take as much time as you need)
