### ISSUE TITLE
[Question] Difference Between the Mods

### ISSUE THREAD

**Issue by Cicopath** [zlainsama/CosmeticArmorReworked#71]
When checking out the files for Cosmetic Armor Reworked, I see two version: v1 and v1-api. What is the difference between these two versions?

**Comment by zlainsama** [comment]
*-api.jar is for developers. You don't need it unless you are developing mods that need to interact with CosmeticArmorReworked.

**Comment by Cicopath** [comment]
Alright, good to know. Thanks for elaborating!
