### ISSUE TITLE
There seems to be no option on 1.18

### ISSUE THREAD

**Issue by Kaye-Potassium** [zlainsama/CosmeticArmorReworked#73]
For some reason, I installed this mod on both server-side and client-side but for some reason, there are no buttons or anything to use the turn on/off armour option.

https://imgur.com/1vjHvVO

**Comment by Kaye-Potassium** [comment]
1.18.2

**Comment by zlainsama** [comment]
I just tested, it all worked on my end with only CosmeticArmorReworked installed.
What mods do you have installed? Also try the keybind to see if that works.

**Comment by Kaye-Potassium** [comment]
Hello! I tried it in single player and I have the same issue (even without the Vampirism button.) https://imgur.com/UaMWcOT

I have the following installed:
- Alex's Mobs
- Appleskin
- Autoreglib
- Balm
- Biomes O'Plenty
- Caelus
- Crayfish Furniture
- Citadel
- Clumps
- Cosmetic Armor
- Druidcraft
- Farmer's Delight
- Fast Leaf Decay
- Jade
- JEI
- Neat+
- Optifine
- Origins
- Quark
- Selene
-  Supplementaries
- TerraBlender
- U Team Core
- Useful Backpacks
- Vampirism
- Waystones 
- Werewolves
- Xaero's Mini Map
- Xaero's World Map

**Comment by zlainsama** [comment]
![2022-04-18_11 46 39](https://user-images.githubusercontent.com/3251859/163751390-eab6b338-7c7c-4373-9d39-0a6747e52592.png)
It works on my end with all the mods you listed above.
Try reinstalling my mod? maybe it got corrupted? Also check the latest.log in logs folder.

**Comment by Kaye-Potassium** [comment]
I reinstalled it, it works perfectly now, tyty!
