### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by ArkSEPlayer** [zlainsama/CosmeticArmorReworked#74]
so, im not sure if youll fix this but im using minecraft 1.7.10.

im having an issue when using dragon block c, when i put the armor(any armor) in the cosmetic slots, for some reason it thinks its normal armor slots? im not sure how to explain it, so ill post a screen shot 

in this screen shot i only have 1 set of diamond armor equipped, which is put in the cosmetic slots, but as you can see, it some reasons "duplicates" in the real/normal armor slots? and it also gives the normal armor defense  as well(as you can see the armor bar at the bottom)

![image](https://user-images.githubusercontent.com/101275010/164614020-06a140d3-73d3-4ae0-bef9-7c49a6aa6e98.png)

**Comment by zlainsama** [comment]
Fixed in 1.7.10-v7.
