### ISSUE TITLE
Can't cancel Mekanism meka-suit's render hand in first-person view

### ISSUE THREAD

**Issue by gisellevonbingen** [zlainsama/CosmeticArmorReworked#82]
I like CosmeticArmorReworked's feature what can set as skin armor.
Just one thing of my hope.
Can't cancel Mekanism's meka-suit's render arm in 1st person view now

Mekanism dev says "require handle RenderArmEvent same with RenderHandEvent" [(From here)](https://github.com/mekanism/Mekanism/pull/7628)
Could you please consider above issue?

I checked already, if mekanism use RenderHandEvent instead of RenderArmEvent,
It was can't render arm.

**Comment by zlainsama** [comment]
Okay, I will add this in 1.18.2 and 1.19.2.
