### ISSUE TITLE
Cosmetic Armor Icon Overlayed on Other Inventory GUIs

### ISSUE THREAD

**Issue by Aiidoneus** [zlainsama/CosmeticArmorReworked#88]
Hello,
Was setting up a Forge test server and noticed an issue which I am guessing could lead to other issues down the road. 

Minecraft: 1.20.1
I am using forge 47.0.3
Cosmetic Armor: cosmeticarmorreworked-1.20.1-v1.jar

Steps to reproduce
1. Hop onto a server and give yourself OP
2. Switch to creative mode
3. Open the creative inventory

![image](https://i.imgur.com/n3hm6f3.png)

This seems to go away after you go back to the survival inventory and then switch back to a creative tab. It does re-appear if you exit out of the inventory totally and then go back to the creative inventory.

I am not sure if other mods are causing this but I am using the All of the Mods 9 modpack on version 0.0.7 if that helps. 

Let me know if you need anymore help testing or need more information.

**Comment by zlainsama** [comment]
Thanks the report. This is an overlook by me.
