### ISSUE TITLE
Port/Compatibility for "Guard Villagers"?

### ISSUE THREAD

**Issue by EagleBlood** [zlainsama/CosmeticArmorReworked#96]
When trying to assign any armour on villagers from "_Guard Villagers_" mod there are weird glitches especially with the helmet. Same story short with decorations. A mod compatibility would be very much appreciated.

**Comment by zlainsama** [comment]
This mod has nothing to do with Villagers.
There must be other mods causing that.

**Comment by EagleBlood** [comment]
Oh sorry my bad.
